[build]
  command = "cd Frontend && npm install && npm run build -- --configuration=production"
  publish = "Frontend/dist/frontend/browser"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200